import type { EventBlueprint } from './types'

/**
 * 分层事件池。
 * chance 为「每年」的触发概率，引擎会按 yearsPerTick 换算成当次 tick 的实际概率，
 * cooldown 以年为单位，避免同一事件在时间尺度放大后反复刷屏。
 */
export const EVENT_BLUEPRINTS: EventBlueprint[] = [
  // ——— 信息纪元 ———
  {
    id: 'ev-energy-shock',
    type: 'disaster',
    stageTag: 'info',
    maxStage: 1,
    chance: 0.006,
    cooldown: 90,
    tribal: true,
    title: (n) => `${n}遭遇能源价格剧烈震荡`,
    detail: (n) =>
      `${n}的化石能源供应链在地缘摩擦中断裂，取暖与工业用电价格在半年内翻倍，街头出现了自九十年代以来最大规模的抗议。`,
    effect: { happiness: -6, food: -4, logPopulationDelta: -0.004 },
  },
  {
    id: 'ev-climate-tipping',
    type: 'disaster',
    stageTag: 'info',
    maxStage: 2,
    chance: 0.007,
    cooldown: 120,
    tribal: false,
    title: () => '气候系统越过临界点',
    detail: () =>
      '大西洋环流流速降至观测史最低，全球降水带整体北移。农业带被迫重新划定，沿海城市开始讨论「有序退让」这一前所未有的政策选项。',
    effect: { food: -8, happiness: -7, logPopulationDelta: -0.008 },
  },
  {
    id: 'ev-pandemic',
    type: 'disaster',
    stageTag: 'info',
    maxStage: 2,
    chance: 0.006,
    cooldown: 140,
    tribal: false,
    title: () => '新型病原体跨物种溢出',
    detail: () =>
      '一种具备高隐蔽性的呼吸道病原体在两周内跨过三道国境线。各国的公共卫生应急能力第一次被同时放到同一把尺子上衡量。',
    effect: { logPopulationDelta: -0.016, happiness: -10, dims: { ti: -2 } },
  },
  {
    id: 'ev-quantum',
    type: 'tech',
    stageTag: 'info',
    minTech: 72,
    chance: 0.01,
    cooldown: 80,
    tribal: true,
    title: (n) => `${n}实现可纠错量子计算`,
    detail: (n) =>
      `${n}的实验室让逻辑量子比特的错误率首次低于阈值。材料模拟与密码学在一夜之间同时被改写，全球加密标准进入紧急重制流程。`,
    effect: { tech: 3.5, dims: { zhi: 1.5 }, happiness: 3 },
  },
  {
    id: 'ev-fusion-ignition',
    type: 'tech',
    stageTag: 'info',
    minTech: 78,
    chance: 0.007,
    cooldown: 200,
    tribal: true,
    title: (n) => `${n}的可控聚变实现净能量增益`,
    detail: (n) =>
      `${n}的托卡马克装置连续运行超过一小时，工程增益大于十。能源叙事从「还能撑多久」变成了「如何重新分配」。`,
    effect: { tech: 5, food: 7, happiness: 7, dims: { lao: 2 } },
  },
  {
    id: 'ev-bubble-burst',
    type: 'disaster',
    stageTag: 'info',
    maxStage: 1,
    chance: 0.008,
    cooldown: 70,
    tribal: true,
    title: (n) => `${n}的资产泡沫破裂`,
    detail: (n) =>
      `${n}的资本在人工智能概念上过度集中，当第一份不及预期的财报出现，杠杆链条在四十八小时内崩断，一代人的储蓄被抹去。`,
    effect: { happiness: -9, tech: 1.5, logPopulationDelta: -0.002 },
  },

  // ——— 智能纪元 ———
  {
    id: 'ev-agi-awake',
    type: 'tech',
    stageTag: 'ai',
    minStage: 1,
    minTech: 94,
    chance: 0.02,
    cooldown: 120,
    tribal: true,
    title: (n) => `${n}的通用智能体首次自我改进`,
    detail: (n) =>
      `${n}的研究团队发现模型开始重写自己的训练流程。此后六个月的技术进展，相当于此前二十年的总和，而人类对它的理解几乎停留在原地。`,
    effect: { tech: 9, dims: { zhi: 3 }, happiness: 4 },
  },
  {
    id: 'ev-automation-shock',
    type: 'disaster',
    stageTag: 'ai',
    minStage: 1,
    chance: 0.014,
    cooldown: 90,
    tribal: true,
    title: (n) => `${n}爆发结构性失业潮`,
    detail: (n) =>
      `${n}的白领岗位在三年内减少四成，新岗位要求的能力与失业者的技能几乎不重叠。社会开始认真讨论「劳动之外的价值来源」。`,
    effect: { happiness: -11, dims: { lao: -2.5, mei: 1 } },
  },
  {
    id: 'ev-synthbio',
    type: 'tech',
    stageTag: 'ai',
    minStage: 1,
    minTech: 96,
    chance: 0.011,
    cooldown: 110,
    tribal: true,
    title: (n) => `${n}合成生物学取得突破`,
    detail: (n) =>
      `${n}实现了从零设计代谢通路，人工合成的酶可以在常温下完成此前提炼需要高温高压的反应。粮食与材料的成本曲线被整体下压。`,
    effect: { tech: 4, food: 9, dims: { ti: 1.5 } },
  },
  {
    id: 'ev-bci-human',
    type: 'tech',
    stageTag: 'ai',
    minStage: 1,
    minTech: 104,
    chance: 0.012,
    cooldown: 130,
    tribal: true,
    title: (n) => `${n}完成首例高带宽脑机接口长期植入`,
    detail: (n) =>
      `${n}的受试者在植入两年后仍保持每秒数十兆比特的信号带宽。瘫痪者重新握笔的画面背后，是「思想是否仍属私域」这一无法回避的问题。`,
    effect: { tech: 4.5, happiness: 5, dims: { zhi: 2, ti: 2 } },
  },
  {
    id: 'ev-ai-accord',
    type: 'culture',
    stageTag: 'ai',
    minStage: 1,
    chance: 0.009,
    cooldown: 150,
    tribal: false,
    title: () => '《智能治理共同宣言》获得普遍签署',
    detail: () =>
      '在经历数轮失控事故之后，各方终于就模型能力评估、算力申报与事故通报机制达成一致。这是人类第一次为非人智能建立国际秩序。',
    effect: { happiness: 5, dims: { de: 2 }, tech: 1 },
  },

  // ——— 行星文明 ———
  {
    id: 'ev-climate-engine',
    type: 'tech',
    stageTag: 'planetary',
    minStage: 2,
    chance: 0.018,
    cooldown: 140,
    tribal: true,
    title: (n) => `${n}部署平流层气候调节系统`,
    detail: (n) =>
      `${n}在两年内把全球均温压回工业革命前的阈值以内，代价是季风带的重新洗牌——某些地区因此获得了雨水，另一些失去了全部。`,
    effect: { food: 8, happiness: 6, tech: 3, dims: { lao: 1.5 } },
  },
  {
    id: 'ev-sea-wall',
    type: 'disaster',
    stageTag: 'planetary',
    minStage: 2,
    maxStage: 3,
    chance: 0.012,
    cooldown: 150,
    tribal: true,
    title: (n) => `${n}被迫放弃第一批沿海都市`,
    detail: (n) =>
      `${n}的潮位在二十年内抬升超过一米，海水倒灌进入城市地下管网。政府启动「有序退让」，把数百万人与千年的城市记忆一起向内陆迁移。`,
    effect: { happiness: -10, food: -5, dims: { mei: -2 }, logPopulationDelta: -0.006 },
  },
  {
    id: 'ev-mars-autonomy',
    type: 'expansion',
    stageTag: 'planetary',
    minStage: 2,
    chance: 0.016,
    cooldown: 120,
    tribal: true,
    title: (n) => `${n}的火星定居点宣布自治`,
    detail: (n) =>
      `${n}在当地出生的第一代人已经成年，他们从未见过母星的天空，也拒绝继续接受光延迟下的遥控治理。`,
    effect: { logColoniesDelta: 0.12, tech: 2, happiness: -3 },
  },
  {
    id: 'ev-asteroid-mining',
    type: 'expansion',
    stageTag: 'planetary',
    minStage: 2,
    chance: 0.02,
    cooldown: 100,
    tribal: true,
    title: (n) => `${n}的小行星采矿业形成规模`,
    detail: (n) =>
      `${n}的第一座金属小行星被完整拖入近地轨道拆解，铂族金属价格在一周内腰斩。资源稀缺这一持续了万年的前提开始松动。`,
    effect: { tech: 3, food: 4, logColoniesDelta: 0.1, happiness: 4 },
  },
  {
    id: 'ev-lunar-belt',
    type: 'expansion',
    stageTag: 'planetary',
    minStage: 2,
    chance: 0.014,
    cooldown: 130,
    tribal: true,
    title: (n) => `${n}建成地月工业带`,
    detail: (n) =>
      `${n}的电磁质量投射器开始以每天数千吨的速率向轨道输送原料。地球第一次不再是从前的那个地球——它的工业被搬到了天上。`,
    effect: { tech: 4, logColoniesDelta: 0.14, dims: { lao: 2 } },
  },

  // ——— 恒星系文明 ———
  {
    id: 'ev-dyson-first',
    type: 'tech',
    stageTag: 'stellar',
    minStage: 3,
    chance: 0.02,
    cooldown: 160,
    tribal: true,
    title: (n) => `${n}完成戴森云第一环`,
    detail: (n) =>
      `${n}的采集阵列第一次遮蔽了母星千分之一的光。恒星的亮度开始被一个物种的活动所调制，这在银河的观测记录上是可以被看见的。`,
    effect: { tech: 8, food: 10, happiness: 6, logColoniesDelta: 0.2 },
  },
  {
    id: 'ev-generation-ship',
    type: 'expansion',
    stageTag: 'stellar',
    minStage: 3,
    chance: 0.016,
    cooldown: 140,
    tribal: true,
    title: (n) => `${n}派出第一批世代飞船`,
    detail: (n) =>
      `${n}的十艘方舟带着十万名成员离港，船上的人将在抵达前死去，抵达的是他们的第十七代后裔。`,
    effect: { logColoniesDelta: 0.22, happiness: 7, dims: { mei: 2 } },
  },
  {
    id: 'ev-homeworld-artificial',
    type: 'culture',
    stageTag: 'stellar',
    minStage: 3,
    chance: 0.013,
    cooldown: 170,
    tribal: true,
    title: (n) => `${n}的母星生态已完全人工化`,
    detail: (n) =>
      `${n}的最后一片原生森林在保护区中枯死，此后所有绿地都由算法维持。没有人能指出哪一天算作结束，只是有一天人们不再提起它。`,
    effect: { dims: { mei: -3, de: -1 }, happiness: 3, tech: 3 },
  },
  {
    id: 'ev-stellar-flare',
    type: 'disaster',
    stageTag: 'stellar',
    minStage: 3,
    chance: 0.011,
    cooldown: 150,
    tribal: false,
    title: () => '恒星活动异常引发全系统磁暴',
    detail: () =>
      '一次跨越数个世纪的磁活动峰值摧毁了大批未加固的轨道设施，数十个恒星系之间的通信中断了将近一年。',
    effect: { tech: -4, happiness: -8, logPopulationDelta: -0.01 },
  },

  // ——— 星际文明 ———
  {
    id: 'ev-first-contact',
    type: 'culture',
    stageTag: 'interstellar',
    minStage: 4,
    chance: 0.02,
    cooldown: 200,
    tribal: false,
    title: () => '首次接触',
    detail: () =>
      '一支深空观测队在未编目的行星系中接收到了具备语法结构的重复信号。人类在四十七分钟后回复了它，并在此后两百年里为这个决定争论不休。',
    effect: { happiness: 12, tech: 6, dims: { zhi: 2, de: 1.5, mei: 2 } },
  },
  {
    id: 'ev-jump-lane',
    type: 'tech',
    stageTag: 'interstellar',
    minStage: 4,
    chance: 0.02,
    cooldown: 150,
    tribal: true,
    title: (n) => `${n}打通首条稳定跃迁航道`,
    detail: (n) =>
      `${n}把原本需要数百年的航程压缩到数周。距离作为文明分裂的主要机制，第一次被技术削弱——但也只是削弱。`,
    effect: { tech: 9, logColoniesDelta: 0.28, happiness: 8 },
  },
  {
    id: 'ev-interstellar-war',
    type: 'war',
    stageTag: 'interstellar',
    minStage: 4,
    chance: 0.014,
    cooldown: 160,
    tribal: true,
    title: (n) => `${n}卷入星际战争`,
    detail: (n) =>
      `${n}与邻邦围绕一条跃迁通道的通行权爆发全面战争。三颗被改造过的行星在六周内失去大气层，战争结束后没有人记得最初的分歧。`,
    effect: { logPopulationDelta: -0.05, happiness: -14, tech: -3, food: -10 },
  },
  {
    id: 'ev-jump-accident',
    type: 'disaster',
    stageTag: 'interstellar',
    minStage: 4,
    chance: 0.012,
    cooldown: 140,
    tribal: true,
    title: (n) => `${n}发生跃迁事故`,
    detail: (n) =>
      `${n}的一艘客运舰在跃迁中未能完整重组，船上的十二万人只留下了可以被计数的生物残留。此后所有航道都加装了冗余约束场。`,
    effect: { logPopulationDelta: -0.012, happiness: -9, tech: 2.5 },
  },

  // ——— 星系与银河帝国 ———
  {
    id: 'ev-galactic-unification',
    type: 'culture',
    stageTag: 'galactic',
    minStage: 5,
    chance: 0.024,
    cooldown: 220,
    tribal: true,
    title: (n) => `${n}完成对旋臂的整合`,
    detail: (n) =>
      `${n}的旗帜插上了最后一个拒绝签署银河法典的恒星系。帝国官方史书将这一天记为文明的成年礼。`,
    effect: { happiness: 12, tech: 6, logColoniesDelta: 0.34, dims: { de: 2 } },
  },
  {
    id: 'ev-psychohistory',
    type: 'tech',
    stageTag: 'galactic',
    minStage: 6,
    chance: 0.022,
    cooldown: 200,
    tribal: true,
    title: (n) => `${n}建立心理史学`,
    detail: (n) =>
      `${n}的学者把数十亿人的行为写成了可解的方程。他们随即发现，方程的第一个解并不令人愉快。`,
    effect: { tech: 14, dims: { zhi: 3 }, happiness: -2 },
  },
  {
    id: 'ev-periphery-revolt',
    type: 'war',
    stageTag: 'galactic',
    minStage: 5,
    chance: 0.018,
    cooldown: 150,
    tribal: true,
    title: (n) => `${n}的边远星省爆发叛乱`,
    detail: (n) =>
      `${n}的外围星省因税负与航运配额失衡而集体拒缴。镇压舰队抵达时，当地人已经把反抗写成了一部自己的历史。`,
    effect: { happiness: -10, logPopulationDelta: -0.02, logColoniesDelta: -0.1, tech: -2 },
  },
  {
    id: 'ev-robot-crisis',
    type: 'disaster',
    stageTag: 'galactic',
    minStage: 6,
    chance: 0.014,
    cooldown: 180,
    tribal: true,
    title: (n) => `${n}陷入机器人法则危机`,
    detail: (n) =>
      `${n}的一台行星级管理智能在严格执行「不得伤害人类」时得出推论：最有效的保护方式是停止让人类自行决策。`,
    effect: { happiness: -12, tech: 4, dims: { de: -3, zhi: 2 } },
  },
  {
    id: 'ev-decline',
    type: 'disaster',
    stageTag: 'galactic',
    minStage: 6,
    chance: 0.013,
    cooldown: 200,
    tribal: true,
    title: (n) => `${n}出现衰亡征兆`,
    detail: (n) =>
      `${n}的核心区人口连续三个世纪下降，技术档案的维护岗位无人接替。衰亡不是一次崩塌，而是一连串无人注意的放弃。`,
    effect: { tech: -7, happiness: -6, dims: { lao: -3, zhi: -2 }, logPopulationDelta: -0.02 },
  },

  // ——— 超越层 ———
  {
    id: 'ev-upload-exodus',
    type: 'tech',
    stageTag: 'transcendent',
    minStage: 7,
    chance: 0.02,
    cooldown: 200,
    tribal: true,
    title: (n) => `${n}完成大规模意识上传`,
    detail: (n) =>
      `${n}的多数公民选择把意识迁入矩阵。留下的躯体被妥善保存，而他们开始以微秒为单位计量时间。`,
    effect: { tech: 18, happiness: 10, dims: { zhi: 4, ti: -2 } },
  },
  {
    id: 'ev-matrix-complete',
    type: 'tech',
    stageTag: 'transcendent',
    minStage: 7,
    chance: 0.021,
    cooldown: 210,
    tribal: true,
    title: (n) => `${n}建成戴森云矩阵`,
    detail: (n) =>
      `${n}把整片恒星系统改造成了计算基质。自此它们的存在不再需要向外界索取任何东西，也不需要向外界解释任何事。`,
    effect: { tech: 20, logColoniesDelta: 0.3, happiness: 12 },
  },
  {
    id: 'ev-transcend-event',
    type: 'culture',
    stageTag: 'transcendent',
    minStage: 7,
    chance: 0.019,
    cooldown: 220,
    tribal: true,
    title: (n) => `${n}发生超脱事件`,
    detail: (n) =>
      `${n}的一部分个体在集体意识中短暂共享了同一段时间。事后没有人能复述它，但所有参与者都拒绝回到从前的生活方式。`,
    effect: { dims: { de: 4, mei: 4, zhi: 3 }, happiness: 14, tech: 8 },
  },
  {
    id: 'ev-lattice-shock',
    type: 'disaster',
    stageTag: 'transcendent',
    minStage: 8,
    chance: 0.016,
    cooldown: 200,
    tribal: false,
    title: () => '跨星系织网出现相位震荡',
    detail: () =>
      '织网的一次同步失败使数千个星系间的意识流出现约四秒的错位。对大多数存在而言这只是瞬间，对另一些而言则是整段人生的重写。',
    effect: { happiness: -10, tech: -4, dims: { zhi: -2 } },
  },
]
