import type { LawBlueprint } from './types'

/**
 * 法律条文池。
 * 每条律法都带有触发条件，由 emergence.ts 在每 tick 末尾按条件判定是否「萌芽」，
 * 因此法律体系是演化涌现出来的，而不是预先排好的时间线。
 */
export const LAW_BLUEPRINTS: LawBlueprint[] = [
  // ——— 信息纪元：2026 年前后自然会补上的现代法 ———
  {
    id: 'law-antitrust',
    title: '《反垄断与公平竞争法》',
    category: 'economic',
    stageTag: 'info',
    strictness: 48,
    enforcement: 46,
    reason: '当少数机构掌握定价权，市场就不再传递真实信号，法律必须重新切分权力。',
    condition: { minTech: 62, dims: { de: { min: 58 } } },
    weight: 1.1,
  },
  {
    id: 'law-ip',
    title: '《知识产权保护法》',
    category: 'economic',
    stageTag: 'info',
    strictness: 42,
    enforcement: 44,
    reason: '创新需要可回收的回报，否则没有人愿意承担失败的成本。',
    condition: { minTech: 58 },
    weight: 1.05,
  },
  {
    id: 'law-education',
    title: '《全民义务教育法》',
    category: 'civil',
    stageTag: 'info',
    strictness: 30,
    enforcement: 58,
    reason: '识字率是工业社会最廉价的国力投资，教育因此从家庭私事变成国家义务。',
    condition: { dims: { de: { min: 56 }, zhi: { min: 55 } } },
    weight: 1.2,
  },
  {
    id: 'law-public-health',
    title: '《公共卫生应急法》',
    category: 'civil',
    stageTag: 'info',
    strictness: 36,
    enforcement: 52,
    reason: '传染不认国界，防疫因此必须以公权力介入个体行动自由。',
    condition: { minPopLog: 8.6 },
    weight: 1,
  },
  {
    id: 'law-labor',
    title: '《劳动者集体谈判权法》',
    category: 'economic',
    stageTag: 'info',
    strictness: 38,
    enforcement: 48,
    reason: '单个劳动者无法与组织议价，集体行动权是力量对等的唯一出路。',
    condition: { dims: { lao: { min: 72 }, de: { min: 60 } } },
    weight: 1.05,
  },
  {
    id: 'law-cyber',
    title: '《网络空间安全法》',
    category: 'criminal',
    stageTag: 'info',
    strictness: 56,
    enforcement: 54,
    reason: '关键基础设施一旦联网，攻击成本骤降，防御必须写进法律。',
    condition: { minTech: 70 },
    weight: 1,
  },
  {
    id: 'law-trafficking',
    title: '《反人口贩运与强迫劳动法》',
    category: 'criminal',
    stageTag: 'info',
    strictness: 72,
    enforcement: 50,
    reason: '把人当作商品是文明最难承认的旧账，法律选择用重刑抹去它。',
    condition: { dims: { de: { min: 62 } } },
    weight: 0.9,
  },
  {
    id: 'law-antibiotic',
    title: '《抗微生物耐药管控条例》',
    category: 'civil',
    stageTag: 'info',
    strictness: 44,
    enforcement: 42,
    reason: '抗生素滥用把细菌变成对手，用药因此从临床自由变成公共管制。',
    condition: { minTech: 68, dims: { zhi: { min: 64 } } },
    weight: 0.85,
  },

  // ——— 智能纪元 ———
  {
    id: 'law-agi-ethics',
    title: '《通用人工智能伦理法》',
    category: 'custom',
    stageTag: 'ai',
    strictness: 62,
    enforcement: 56,
    reason: '当系统开始自行制定目标，人类第一次需要给非人主体划定边界。',
    condition: { minStage: 1, minTech: 96 },
    weight: 1.6,
  },
  {
    id: 'law-algo-accountability',
    title: '《算法透明与问责条例》',
    category: 'civil',
    stageTag: 'ai',
    strictness: 46,
    enforcement: 58,
    reason: '不可解释的决策等于不可追责的权力，透明成为新的合法性来源。',
    condition: { minTech: 92 },
    weight: 1.3,
  },
  {
    id: 'law-gene-edit',
    title: '《生殖系基因编辑禁令》',
    category: 'custom',
    stageTag: 'ai',
    strictness: 70,
    enforcement: 62,
    reason: '可遗传的修改把个体选择变成物种决定，人类选择先按下暂停。',
    condition: { minTech: 99, dims: { de: { min: 60 } } },
    weight: 1.2,
  },
  {
    id: 'law-ubi',
    title: '《全民基本保障法》',
    category: 'economic',
    stageTag: 'ai',
    strictness: 34,
    enforcement: 60,
    reason: '自动化使劳动不再是分配的凭据，社会必须找到新的分配理由。',
    condition: { minTech: 94, dims: { lao: { min: 80 } } },
    weight: 1.35,
  },
  {
    id: 'law-bci-privacy',
    title: '《神经数据保护法》',
    category: 'civil',
    stageTag: 'ai',
    strictness: 58,
    enforcement: 52,
    reason: '思想一旦可被读取，隐私的最后一道墙也就消失了。',
    condition: { minTech: 108 },
    weight: 1.25,
  },
  {
    id: 'law-aw-ban',
    title: '《自主武器系统禁令》',
    category: 'military',
    stageTag: 'ai',
    strictness: 74,
    enforcement: 44,
    reason: '把开火权交给算法，等于把战争的门槛降到零。',
    condition: { minTech: 98, dims: { de: { min: 68 } } },
    weight: 1.1,
  },

  // ——— 行星文明 ———
  {
    id: 'law-climate-eng',
    title: '《气候工程管控公约》',
    category: 'economic',
    stageTag: 'planetary',
    strictness: 54,
    enforcement: 58,
    reason: '谁掌握了平流层的开关，谁就掌握了所有人的降雨。',
    condition: { minStage: 2 },
    weight: 1.5,
  },
  {
    id: 'law-orbit-property',
    title: '《轨道与地外资源登记法》',
    category: 'economic',
    stageTag: 'planetary',
    strictness: 44,
    enforcement: 52,
    reason: '当开采成本低于运输成本，资源争夺就从地球搬到了轨道。',
    condition: { minStage: 2, minTech: 104 },
    weight: 1.3,
  },
  {
    id: 'law-biosphere',
    title: '《行星生态修复强制义务法》',
    category: 'custom',
    stageTag: 'planetary',
    strictness: 58,
    enforcement: 60,
    reason: '文明终于承认：母星的修复成本远低于迁移成本。',
    condition: { minStage: 2, dims: { de: { min: 70 }, mei: { min: 68 } } },
    weight: 1.2,
  },
  {
    id: 'law-colony-charter',
    title: '《地外定居点自治章程》',
    category: 'civil',
    stageTag: 'planetary',
    strictness: 36,
    enforcement: 48,
    reason: '距离会稀释主权，殖民地迟早要求自己决定自己的税率。',
    condition: { minStage: 2, minColoniesLog: 1 },
    weight: 1.25,
  },

  // ——— 恒星系文明 ———
  {
    id: 'law-dyson-charter',
    title: '《戴森云建设与共享公约》',
    category: 'economic',
    stageTag: 'stellar',
    strictness: 48,
    enforcement: 62,
    reason: '遮蔽一颗恒星影响的是整个系统，能源因此成为第一项真正的公共品。',
    condition: { minStage: 3 },
    weight: 1.6,
  },
  {
    id: 'law-terraform-ethics',
    title: '《行星改造伦理准则》',
    category: 'custom',
    stageTag: 'stellar',
    strictness: 60,
    enforcement: 54,
    reason: '改造一颗有原生生命的星球，与灭绝一个世界没有区别。',
    condition: { minStage: 3, dims: { de: { min: 72 } } },
    weight: 1.3,
  },
  {
    id: 'law-flight-control',
    title: '《恒星系间航行管制法》',
    category: 'civil',
    stageTag: 'stellar',
    strictness: 52,
    enforcement: 60,
    reason: '一次导航误差在恒星尺度上就是一次文明事故。',
    condition: { minStage: 3, minTech: 130 },
    weight: 1.4,
  },
  {
    id: 'law-heritage-star',
    title: '《母星遗产不可开采法》',
    category: 'custom',
    stageTag: 'stellar',
    strictness: 66,
    enforcement: 56,
    reason: '当故乡只剩考古价值，把它挖空就等于删掉文明的出处。',
    condition: { minStage: 3, dims: { mei: { min: 75 } } },
    weight: 1.15,
  },

  // ——— 星际文明 ———
  {
    id: 'law-interstellar-war',
    title: '《星际战争限制法》',
    category: 'military',
    stageTag: 'interstellar',
    strictness: 68,
    enforcement: 50,
    reason: '能被摧毁的恒星太多，战争必须重新被定义为非法行为。',
    condition: { minStage: 4 },
    weight: 1.5,
  },
  {
    id: 'law-jump-registry',
    title: '《跃迁通道登记与仲裁法》',
    category: 'civil',
    stageTag: 'interstellar',
    strictness: 46,
    enforcement: 58,
    reason: '通道是稀缺的，谁先登记谁先通行，否则每次跃迁都是一场冲突。',
    condition: { minStage: 4, minTech: 152 },
    weight: 1.4,
  },
  {
    id: 'law-trade-standard',
    title: '《跨恒星系贸易标准法》',
    category: 'economic',
    stageTag: 'interstellar',
    strictness: 40,
    enforcement: 62,
    reason: '度量衡不统一，星际贸易就永远停在以物易物的水平。',
    condition: { minStage: 4 },
    weight: 1.45,
  },
  {
    id: 'law-sleeper-rights',
    title: '《休眠移民权利保障法》',
    category: 'civil',
    stageTag: 'interstellar',
    strictness: 42,
    enforcement: 54,
    reason: '一个人沉睡三百年后醒来，他还是出发时的那个人吗？法律必须回答。',
    condition: { minStage: 4, dims: { de: { min: 75 } } },
    weight: 1.2,
  },

  // ——— 星系与银河帝国 ———
  {
    id: 'law-galactic-code',
    title: '《银河法典 · 总则》',
    category: 'custom',
    stageTag: 'galactic',
    strictness: 50,
    enforcement: 66,
    reason: '数亿个恒星系需要同一套语言来定义「合法」，否则统一只是军事事实。',
    condition: { minStage: 5 },
    weight: 1.8,
  },
  {
    id: 'law-robot-laws',
    title: '《机器三定律》',
    category: 'custom',
    stageTag: 'galactic',
    strictness: 78,
    enforcement: 72,
    reason: '当机器人数量超过人类，给机器立宪比给人立法更紧迫。',
    condition: { minStage: 5, minTech: 170 },
    weight: 1.7,
  },
  {
    id: 'law-pre-civ',
    title: '《前文明保护区禁令》',
    category: 'custom',
    stageTag: 'galactic',
    strictness: 80,
    enforcement: 58,
    reason: '不干预比自己原始的文明，是强者唯一体面的自我约束。',
    condition: { minStage: 5, dims: { de: { min: 80 } } },
    weight: 1.4,
  },
  {
    id: 'law-psychohistory',
    title: '《心理史学应用监管法》',
    category: 'custom',
    stageTag: 'galactic',
    strictness: 62,
    enforcement: 64,
    reason: '能预测百万人的集体行为，就等于掌握了比武力更彻底的控制手段。',
    condition: { minStage: 6, dims: { zhi: { min: 88 } } },
    weight: 1.55,
  },
  {
    id: 'law-senate',
    title: '《星系议会代表制条例》',
    category: 'civil',
    stageTag: 'galactic',
    strictness: 34,
    enforcement: 60,
    reason: '没有代表权的省份不会忠于帝国，离心力从不是从外部开始的。',
    condition: { minStage: 6 },
    weight: 1.6,
  },
  {
    id: 'law-tariff',
    title: '《帝国关税统一条例》',
    category: 'economic',
    stageTag: 'galactic',
    strictness: 44,
    enforcement: 68,
    reason: '统一税则是帝国唯一能同时被商人和总督接受的治理工具。',
    condition: { minStage: 6, minTech: 190 },
    weight: 1.3,
  },

  // ——— 超越层 ———
  {
    id: 'law-upload-personhood',
    title: '《意识上传者法律人格认定法》',
    category: 'civil',
    stageTag: 'transcendent',
    strictness: 46,
    enforcement: 62,
    reason: '当记忆可以复制，人格的同一性只能由法律来定义。',
    condition: { minStage: 7 },
    weight: 1.5,
  },
  {
    id: 'law-matrix-protocol',
    title: '《跨星系织网协议》',
    category: 'economic',
    stageTag: 'transcendent',
    strictness: 40,
    enforcement: 66,
    reason: '矩阵之间的延迟就是文明的心跳，协议决定了它是否还算一个整体。',
    condition: { minStage: 7 },
    weight: 1.45,
  },
  {
    id: 'law-no-delete',
    title: '《意识存档不可删除条约》',
    category: 'custom',
    stageTag: 'transcendent',
    strictness: 84,
    enforcement: 60,
    reason: '删除一份存档与谋杀的区别，只在于它是否还算一个人。',
    condition: { minStage: 7, dims: { de: { min: 85 } } },
    weight: 1.35,
  },
  {
    id: 'law-entropy',
    title: '《熵平衡与宇宙尺度资源公约》',
    category: 'economic',
    stageTag: 'transcendent',
    strictness: 56,
    enforcement: 58,
    reason: '当能量不再稀缺，稀缺的变成了可用的低熵，而它终究是有限的。',
    condition: { minStage: 8 },
    weight: 1.4,
  },
]
