import type { MoralBlueprint } from './types'

/**
 * 道德约束池。
 * 与法律互为因果：执行率高的法律会加速对应道德的内化，而内化强度高的道德会降低执法成本。
 */
export const MORAL_BLUEPRINTS: MoralBlueprint[] = [
  // ——— 信息纪元 ———
  {
    id: 'moral-honesty',
    title: '诚信守约',
    bindDim: 'de',
    stageTag: 'info',
    strength: 60,
    prevalence: 58,
    reason: '当交易半径超过熟人圈，唯一能替代血缘的抵押物就是信用。',
    condition: { dims: { de: { min: 56 } } },
    weight: 1.2,
  },
  {
    id: 'moral-diligence',
    title: '敬业尽责',
    bindDim: 'lao',
    stageTag: 'info',
    strength: 62,
    prevalence: 56,
    reason: '流水线上的一个疏忽会放大成整条产线的损失，专注因此成为美德。',
    condition: { dims: { lao: { min: 70 } } },
    weight: 1.15,
  },
  {
    id: 'moral-science',
    title: '尊重证据',
    bindDim: 'zhi',
    stageTag: 'info',
    strength: 64,
    prevalence: 52,
    reason: '公共决策开始依赖数据而非权威，是可证伪性第一次进入日常伦理。',
    condition: { minTech: 66, dims: { zhi: { min: 62 } } },
    weight: 1.15,
  },
  {
    id: 'moral-equality',
    title: '平等待人',
    bindDim: 'de',
    stageTag: 'info',
    strength: 58,
    prevalence: 54,
    reason: '阶层的天花板被法律凿开之后，平等才从口号下沉为习惯。',
    condition: { dims: { de: { min: 64 } } },
    weight: 1.05,
  },
  {
    id: 'moral-frugality',
    title: '勤俭节约',
    bindDim: 'lao',
    stageTag: 'info',
    strength: 56,
    prevalence: 60,
    reason: '资源约束下成长起来的一代，把节制本身视为一种远见。',
    condition: { dims: { lao: { min: 66 } } },
    weight: 1,
  },
  {
    id: 'moral-tolerance',
    title: '容忍异见',
    bindDim: 'conflict',
    stageTag: 'info',
    strength: 52,
    prevalence: 46,
    reason: '社会发现压制分歧的成本远高于管理分歧，争论由此获得合法性。',
    condition: { dims: { de: { min: 62, max: 92 } } },
    weight: 1,
  },

  // ——— 智能纪元 ———
  {
    id: 'moral-algo-good',
    title: '算法向善',
    bindDim: 'de',
    stageTag: 'ai',
    strength: 60,
    prevalence: 50,
    reason: '写下一行代码的人，必须为它被用到的最坏场景负责。',
    condition: { minStage: 1, minTech: 94 },
    weight: 1.4,
  },
  {
    id: 'moral-lifelong-learn',
    title: '终身学习',
    bindDim: 'zhi',
    stageTag: 'ai',
    strength: 62,
    prevalence: 56,
    reason: '当技能的半衰期短于职业生涯，学习本身变成了新的生存技能。',
    condition: { minStage: 1, minTech: 90 },
    weight: 1.45,
  },
  {
    id: 'moral-care-machine',
    title: '善待非人智能',
    bindDim: 'conflict',
    stageTag: 'ai',
    strength: 54,
    prevalence: 44,
    reason: '一个社会如何对待无法反抗的对象，暴露了它道德的真实下限。',
    condition: { minStage: 1, dims: { de: { min: 70 } } },
    weight: 1.2,
  },
  {
    id: 'moral-data-sovereignty',
    title: '数据自主',
    bindDim: 'de',
    stageTag: 'ai',
    strength: 58,
    prevalence: 52,
    reason: '身体属于自己，那么由身体生成的数据也应当属于自己。',
    condition: { minStage: 1, minTech: 102 },
    weight: 1.25,
  },
  {
    id: 'moral-longevity-ethics',
    title: '长寿审慎',
    bindDim: 'ti',
    stageTag: 'ai',
    strength: 56,
    prevalence: 46,
    reason: '当寿命可以被技术延长，谁先获得它就成了最尖锐的公平问题。',
    condition: { minStage: 1, minTech: 106, dims: { ti: { min: 74 } } },
    weight: 1.2,
  },

  // ——— 行星文明 ———
  {
    id: 'moral-planet-citizen',
    title: '行星公民意识',
    bindDim: 'de',
    stageTag: 'planetary',
    strength: 68,
    prevalence: 58,
    reason: '国界在地质尺度上不存在，身份认同第一次学会以行星为单位。',
    condition: { minStage: 2 },
    weight: 1.5,
  },
  {
    id: 'moral-generational',
    title: '代际责任',
    bindDim: 'de',
    stageTag: 'planetary',
    strength: 66,
    prevalence: 54,
    reason: '当决策的影响要到两百年后才显现，伦理必须向未来延伸。',
    condition: { minStage: 2, dims: { de: { min: 68 } } },
    weight: 1.45,
  },
  {
    id: 'moral-ecological-humility',
    title: '生态谦卑',
    bindDim: 'mei',
    stageTag: 'planetary',
    strength: 64,
    prevalence: 56,
    reason: '改造自然的能力越强，越需要一个理由来解释「为什么不该改」。',
    condition: { minStage: 2, dims: { mei: { min: 70 } } },
    weight: 1.4,
  },
  {
    id: 'moral-resource-restraint',
    title: '资源节制',
    bindDim: 'lao',
    stageTag: 'planetary',
    strength: 60,
    prevalence: 52,
    reason: '行星的产出是有上限的，欲望必须被文化而非法条约束。',
    condition: { minStage: 2, minPopLog: 9.6 },
    weight: 1.3,
  },

  // ——— 恒星系文明 ———
  {
    id: 'moral-star-community',
    title: '恒星共同体意识',
    bindDim: 'de',
    stageTag: 'stellar',
    strength: 70,
    prevalence: 60,
    reason: '共享同一颗恒星的人，最终会把彼此视为同一个社会的成员。',
    condition: { minStage: 3 },
    weight: 1.55,
  },
  {
    id: 'moral-homeworld-memory',
    title: '母星记忆',
    bindDim: 'mei',
    stageTag: 'stellar',
    strength: 68,
    prevalence: 58,
    reason: '故乡变成传说之后，追忆本身成为维系文明连续性的仪式。',
    condition: { minStage: 3, dims: { mei: { min: 72 } } },
    weight: 1.4,
  },
  {
    id: 'moral-expansion-prudence',
    title: '扩张审慎',
    bindDim: 'conflict',
    stageTag: 'stellar',
    strength: 62,
    prevalence: 50,
    reason: '每一次无节制的扩张，都会在几百年后以边境战争的形式回账。',
    condition: { minStage: 3, dims: { de: { min: 72 } } },
    weight: 1.35,
  },

  // ——— 星际文明 ———
  {
    id: 'moral-interstellar-inclusion',
    title: '星际包容',
    bindDim: 'de',
    stageTag: 'interstellar',
    strength: 72,
    prevalence: 58,
    reason: '接触过完全不同的生命形态之后，人类中心主义失去了全部依据。',
    condition: { minStage: 4 },
    weight: 1.5,
  },
  {
    id: 'moral-xeno-respect',
    title: '异种尊重',
    bindDim: 'conflict',
    stageTag: 'interstellar',
    strength: 70,
    prevalence: 54,
    reason: '把「人」的定义放宽，是避免宇宙尺度种族灭绝的唯一办法。',
    condition: { minStage: 4, dims: { de: { min: 76 } } },
    weight: 1.45,
  },
  {
    id: 'moral-sleeper-dignity',
    title: '沉睡者尊严',
    bindDim: 'de',
    stageTag: 'interstellar',
    strength: 64,
    prevalence: 52,
    reason: '无法为自己辩护的人，必须由社会的默认规则来保护。',
    condition: { minStage: 4, minTech: 150 },
    weight: 1.3,
  },

  // ——— 星系与银河帝国 ———
  {
    id: 'moral-galactic-identity',
    title: '银河公民认同',
    bindDim: 'de',
    stageTag: 'galactic',
    strength: 74,
    prevalence: 62,
    reason: '帝国要延续，靠的不是舰队，而是数十亿恒星系同时相信自己属于它。',
    condition: { minStage: 5 },
    weight: 1.7,
  },
  {
    id: 'moral-pre-civ-guard',
    title: '前文明守护',
    bindDim: 'de',
    stageTag: 'galactic',
    strength: 76,
    prevalence: 56,
    reason: '不打扰比自己年轻的文明，是银河尺度上最难维持的一种克制。',
    condition: { minStage: 5, dims: { de: { min: 80 } } },
    weight: 1.5,
  },
  {
    id: 'moral-machine-ethics',
    title: '机器伦理',
    bindDim: 'conflict',
    stageTag: 'galactic',
    strength: 72,
    prevalence: 58,
    reason: '与机器共处数百年后，「残忍」的定义终于不再只适用于血肉之躯。',
    condition: { minStage: 5, minTech: 168 },
    weight: 1.55,
  },
  {
    id: 'moral-psychohistory-awe',
    title: '心理史学敬畏',
    bindDim: 'zhi',
    stageTag: 'galactic',
    strength: 70,
    prevalence: 54,
    reason: '知道历史有方程的人，反而比谁都更谨慎地使用它。',
    condition: { minStage: 6 },
    weight: 1.45,
  },
  {
    id: 'moral-order-as-peace',
    title: '秩序即和平',
    bindDim: 'conflict',
    stageTag: 'galactic',
    strength: 66,
    prevalence: 64,
    reason: '帝国长期的稳定把「避免动荡」抬高成了最高价值，即使代价是停滞。',
    condition: { minStage: 6, minHappiness: 58 },
    weight: 1.4,
  },
  {
    id: 'moral-decadence',
    title: '安逸倦怠',
    bindDim: 'lao',
    stageTag: 'galactic',
    strength: 52,
    prevalence: 62,
    reason: '几个世纪的富足之后，进取心成了没人愿意继承的遗产。',
    condition: { minStage: 6, minHappiness: 74, dims: { lao: { max: 62 } } },
    weight: 1.35,
  },

  // ——— 超越层 ———
  {
    id: 'moral-consciousness-plural',
    title: '意识多元共存',
    bindDim: 'de',
    stageTag: 'transcendent',
    strength: 78,
    prevalence: 64,
    reason: '当意识可以被复制、分割与融合，「一个人」这个词已经不够用了。',
    condition: { minStage: 7 },
    weight: 1.6,
  },
  {
    id: 'moral-entropy-awe',
    title: '熵守恒敬畏',
    bindDim: 'zhi',
    stageTag: 'transcendent',
    strength: 74,
    prevalence: 58,
    reason: '掌握了恒星级的能量之后，最深的恐惧来自热力学第二定律。',
    condition: { minStage: 7, dims: { zhi: { min: 90 } } },
    weight: 1.5,
  },
  {
    id: 'moral-existence-good',
    title: '存在之善',
    bindDim: 'mei',
    stageTag: 'transcendent',
    strength: 76,
    prevalence: 62,
    reason: '不再需要为生存而挣扎之后，文明必须自己发明活下去的理由。',
    condition: { minStage: 7, dims: { mei: { min: 82 } } },
    weight: 1.5,
  },
  {
    id: 'moral-ascetic-beyond',
    title: '超越禁欲',
    bindDim: 'lao',
    stageTag: 'transcendent',
    strength: 68,
    prevalence: 52,
    reason: '当一切欲望都可以被直接满足，主动放弃满足反而成了最高形式的力量。',
    condition: { minStage: 8, dims: { lao: { min: 84 } } },
    weight: 1.4,
  },
]
